import React from 'react';
import { storiesOf, action } from '@kadira/storybook';

// This file should NOT be included as part of the product code on client or server

// It is ONLY for fast-build of dev components for React Storybook stories: 
//    https://getstorybook.io/docs/react-storybook/basics/writing-stories

// This is included by app/.storybook/config.js

// It is for devs:
//    Run the usual meteor build in one shell (go.sh etc)
//    Run storybook in another shell as follows:
//        npm run storybook            
//        (open browser window to port suggested, for example http://localhost:9001)


// This is useful for mocking the data for the ___Route.js components that get 
// user-related data loaded by Meteor. 
// This was generated by just dumping JSON.stringify($r.props) from 
// the <UserAssetListRoute/> component with the URL http://localhost:3000/u/dgolds/assets
// You can make other mocks in a similar way and check them in for convenience
import fakeAppRouteProps from './__stories_mockAppProps_dgolds.json'
fakeAppRouteProps.handleSetCurrentlyEditingAssetInfo = action('Invoked handleSetCurrentlyEditingAssetInfo')

// BUT Note that you cannot (yet) use any components that import Meteor
// function using the format of ' import from "meteor/foo" '. 
// Hey, that's a Good Reason to keep stuff well abstracted :)

// Here's a test of the simple
import DashboardRoute from './routes/Dashboard/DashboardRoute'

storiesOf('DashBoard', module)
  .add('Dashboard', () => <DashboardRoute {...fakeAppRouteProps}/>)
